name: build and test java code quality
inputs:
  working-directory:
    description: 'working directory'
    required: false
    default: '.'
# checkout code, setup java, build with maven, run checkstyle
runs:
  using: "composite"
  steps:
    - name: run checkstyle
    - run: mvn checkstyle:checkstyle
      working-directory: ${{ inputs.working-directory }}

    - name: combine results into a artefact
    - run: mkdir artifact && cp target/site/checkstyle.html report.html