name: build java app

on:
    push:
        branches:
        - main
    pull_request:
        branches:
        - main


jobs:
    build:
      runs-on: ubuntu-latest

      steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-java@v3
        with:
          distribution: 'temurin'
          java-version: '17'
          cache: 'maven'
      - name: Build with Maven
        working-directory: java-app
        run: mvn --batch-mode --update-snapshots package
      - name: Prepare Artifact
        run: mkdir artifact && cp target/*.jar artifact

      - uses: actions/upload-artifact@v4
        with:
          name: artefact upload
          path: artifact
