name: build java app

on:
    push:
        branches:
        - main
    pull_request:
        branches:
        - main


jobs:
    build:
      runs-on: ubuntu-latest
      defaults:
        run:
          working-directory: java-app
      steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-java@v3
        with:
          distribution: 'temurin'
          java-version: '21'
          cache: 'maven'
      - name: Build with Maven
        run: mvn --batch-mode --update-snapshots package
      - name: Prepare Artifact
        run: mkdir artifact && cp target/*.jar artifact

      - uses: actions/upload-artifact@v4
        with:
          name: artefact upload
          path: artifact
      - uses: ./.github/actions/code-quality-java/action.yml@main
        with:
          working-directory: java-app