name: Greetings

on:
  pull_request:
    types:
      - opened
  issues:
    types:
      - opened
      - reopened

permissions:
  issues: write
  pull-requests: write


jobs:
  greeting:
    name: Greet First-Time Contributors
    runs-on: ubuntu-latest

    steps:
      - uses: actions/first-interaction@v3
        with:
          repo_token: ${{ secrets.GITHUB_TOKEN }}
          issue_message: |
            # Issue Message with Markdown

            This is the message that will be displayed!
          pr_message: |
            # PR Message with Markdown

            This is the message that will be displayed!