name: single vs multiple events

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main
  label:
    types:
      - created
      - labeled
  issues:
    types:
      - created

jobs:
  build:
      runs-on: ubuntu-latest
      steps:
      - uses: actions/checkout@v4
      - name: run one one line script
        run: echo "Hello, world!"